name: ci
on:
  pull_request:
    branches: 
      - master
      - main
      - devel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.x
      - run: pip install scipy
      - run: pip install numpy
      - run: pip install mkdocs-material
      - run: pip install mkdocstrings[python]
      - run: mkdocs gh-deploy --force
